### ISSUE TITLE
Re-pivot master table

### ISSUE THREAD

**Issue by victorlin** [zhoulab/p53-chip-seq-data#11]
## immediate columns

* chr
* start
* end
* repeat_count
* peak_length
* repeat_proportion
* detailed_annotation
* annotation
* repeat_type
* gene
* [sample 1]
* ...
* [sample n]

##  additional columns

* sample_count
* P53match_score_max
* MACS_max
* FE_max
* P53match_score_all
* MACS_all
* FE_all

**Comment by victorlin** [comment]
@varsh1090 since I added the `maxMACS` and `maxFE` columns back, do we also want the `MACS_all` and `FE_all` columns?

**Comment by varsh1090** [comment]
We may not need it for now, but we might later so I would maybe make a different version later if needed.

**Comment by varsh1090** [comment]
Hi Victor, are the maxMACS and maxFE columns added to the master table now?

**Comment by victorlin** [comment]
Yes, those 2 columns have been added.

**Comment by varsh1090** [comment]
Is this the updated script to use - 
[v.sundaresan@login3 p53-chip-seq-data]$ make results/datafiles/ChIP_master_table_macs.txt
make: `results/datafiles/ChIP_master_table_macs.txt' is up to date.
[v.sundaresan@login3 p53-chip-seq-data]$ pwd
/ufrc/zhou/share/projects/bioinformatics/p53/p53-chip-seq-data
The output does not show the MACS_max column.
