### ISSUE TITLE
Update script for new MAST files

### ISSUE THREAD

**Issue by victorlin** [zhoulab/p53-chip-seq-data#26]
New MAST files are in same format and location (`data/MAST`). Filenames end in `_meme-chip_mast.txt`. Data file script should look for `_meme-chip_mast` and omit it from the feature name.

**Comment by varsh1090** [comment]
Please let me know if you have results with the new MAST files, thanks.

**Comment by victorlin** [comment]
I found another issue with the script, and need to fix it first before generating the plots. I will let you know once they are ready.

**Comment by victorlin** [comment]
![all_weights_svc_nonrep](https://user-images.githubusercontent.com/13424970/45601463-3bf9c080-b9db-11e8-9a13-e98d7bdf6e7d.png)

![all_weights_svc_rep](https://user-images.githubusercontent.com/13424970/45601466-41570b00-b9db-11e8-90ad-826dd1d17461.png)

**Comment by victorlin** [comment]
These are some preliminary results with the new files. I am running a new method called Recursive Feature Elimination. It iteratively removes least-contributing features one-by-one and gives rankings based on the order of elimination. Hopefully these results can be used for my presentation tomorrow.
